server/journeys/referral/details/view-proactive.njk, server/journeys/referral/details/view-reactive.njk, server/utils/datetimeUtils.ts, server/utils/nunjucksSetup.ts
=> MIC-253 Restrict referral/details datepicker to dates up to today

server/journeys/referral/contributory-factors-comments/tests.test.ts, server/journeys/referral/contributory-factors-comments/view.njk
=> MIC-291 Update layout of referral/contributory-factors-comments screen

esbuild/esbuild.config.js, server/jest.config.js, server/journeys/jest.config.js, server/routes/csip-records/components/proactive.njk, server/routes/csip-records/components/reactive.njk, server/routes/csip-records/components/referral.njk, server/routes/csip-records/controller.ts, server/routes/csip-records/routes.ts, server/routes/csip-records/tests.test.ts, server/routes/csip-records/view.njk, server/routes/index.ts, server/utils/nunjucksSetup.ts, server/views/partials/layout.njk
=> MIC-297 csip-records/recordUuid page

assets/scss/local.scss, server/@types/express/index.d.ts, server/journeys/record-investigation/controller.ts, server/journeys/record-investigation/routes.ts, server/journeys/record-investigation/start/routes.ts, server/journeys/record-investigation/start/tests.test.ts, server/journeys/record-investigation/tests.test.ts, server/journeys/record-investigation/view.njk, server/journeys/screen/check-answers/view.njk, server/journeys/start/controller.ts, server/routes/journeyRoutes.ts, server/utils/nunjucksSetup.ts
=> MIC-302 record-investigation main screen

server/journeys/record-investigation/routes.ts, server/journeys/record-investigation/staff-involved/controller.ts, server/journeys/record-investigation/staff-involved/routes.ts, server/journeys/record-investigation/staff-involved/schemas.ts, server/journeys/record-investigation/staff-involved/tests.test.ts, server/journeys/record-investigation/staff-involved/view.njk
=> MIC-303 record-investigation/staff-involved screen

server/journeys/referral/details/tests.test.ts, server/journeys/referral/details/view.njk, server/middleware/validationMiddleware.ts, server/utils/nunjucksSetup.ts, server/views/partials/formErrorSummary.njk
=> bug fix: custom ordering of error message

README.md, integration_tests/mockApis/csipApi.ts, server/@types/csip/index.d.ts, server/journeys/referral/check-answers/tests.test.ts, server/journeys/screen/check-answers/controller.ts, server/journeys/screen/check-answers/tests.test.ts, server/journeys/screen/confirmation/controller.ts, server/journeys/screen/confirmation/tests.test.ts, server/journeys/screen/confirmation/view.njk, server/utils/csipDisplayTextUtils.ts, server/utils/nunjucksSetup.ts
=> MIC-387 Use calculated status field for IaR screening confirmation page

integration_tests/utils/e2eTestUtils.ts, server/@types/express/index.d.ts, server/journeys/record-investigation/check-answers/controller.ts, server/journeys/record-investigation/check-answers/routes.ts, server/journeys/record-investigation/check-answers/tests.cy.ts, server/journeys/record-investigation/check-answers/view.njk, server/journeys/record-investigation/delete-interview/controller.ts, server/journeys/record-investigation/routes.ts, server/journeys/screen/check-answers/controller.ts, server/journeys/screen/check-answers/view.njk, server/routes/index.ts
=> MIC-312 record-investigation/check-answers screen

integration_tests/mockApis/csipApi.ts, server/@types/express/index.d.ts, server/routes/journeys/record-decision/controller.ts, server/routes/journeys/record-decision/routes.ts, server/routes/journeys/record-decision/schemas.ts, server/routes/journeys/record-decision/start/routes.ts, server/routes/journeys/record-decision/start/tests.cy.ts, server/routes/journeys/record-decision/tests.cy.ts, server/routes/journeys/record-decision/view.njk, server/routes/journeys/record-investigation/start/tests.test.ts, server/routes/journeys/routes.ts, server/routes/journeys/screen/start/tests.test.ts, server/routes/journeys/start/controller.ts
=> MIC-315 IaR Decision - /record-decision screen

server/routes/journeys/record-decision/next-steps/controller.ts, server/routes/journeys/record-decision/next-steps/routes.ts, server/routes/journeys/record-decision/next-steps/schemas.ts, server/routes/journeys/record-decision/next-steps/tests.cy.ts, server/routes/journeys/record-decision/next-steps/view.njk, server/routes/journeys/record-decision/routes.ts
=> MIC-317 record-decision/next-steps screen

server/routes/journeys/record-decision/additional-information/controller.ts, server/routes/journeys/record-decision/additional-information/routes.ts, server/routes/journeys/record-decision/additional-information/schemas.ts, server/routes/journeys/record-decision/additional-information/tests.cy.ts, server/routes/journeys/record-decision/additional-information/view.njk, server/routes/journeys/record-decision/routes.ts
=> MIC-318 record-decision/additional-information screen

server/routes/journeys/record-decision/additional-information/tests.cy.ts, server/routes/journeys/record-decision/check-answers/controller.ts, server/routes/journeys/record-decision/check-answers/routes.ts, server/routes/journeys/record-decision/check-answers/tests.cy.ts, server/routes/journeys/record-decision/check-answers/view.njk, server/routes/journeys/record-decision/conclusion/controller.ts, server/routes/journeys/record-decision/conclusion/tests.cy.ts, server/routes/journeys/record-decision/next-steps/tests.cy.ts, server/routes/journeys/record-decision/routes.ts, server/routes/journeys/record-decision/tests.cy.ts
=> MIC-319 /record-decision/check-answers screen

server/@types/express/index.d.ts, server/routes/csip-records/controller.ts, server/routes/csip-records/csip-records.cy.ts, server/routes/journeys/develop-an-initial-plan/controller.ts, server/routes/journeys/develop-an-initial-plan/routes.ts, server/routes/journeys/develop-an-initial-plan/schemas.ts, server/routes/journeys/develop-an-initial-plan/start/routes.ts, server/routes/journeys/develop-an-initial-plan/start/tests.cy.ts, server/routes/journeys/develop-an-initial-plan/tests.cy.ts, server/routes/journeys/develop-an-initial-plan/view.njk, server/routes/journeys/routes.ts, server/routes/journeys/start/controller.ts
=> MIC-445 /develop-an-initial-plan screen

integration_tests/e2e/screen-a-csip.cy.ts, integration_tests/mockApis/csipApi.ts, server/@types/csip/index.d.ts, server/routes/journeys/record-decision/check-answers/tests.cy.ts, server/routes/journeys/record-decision/conclusion/controller.ts, server/routes/journeys/record-decision/conclusion/schemas.ts, server/routes/journeys/record-decision/conclusion/tests.cy.ts, server/routes/journeys/referral/check-answers/tests.cy.ts, server/routes/journeys/screen/check-answers/tests.cy.ts, server/routes/journeys/screen/controller.ts, server/routes/journeys/screen/schemas.ts, server/routes/journeys/screen/tests.cy.ts
=> MIC-460 outcome-type => screening-outcome-type and decision-outcome-type

server/routes/journeys/develop-an-initial-plan/routes.ts, server/routes/journeys/develop-an-initial-plan/summarise-identified-need/controller.ts, server/routes/journeys/develop-an-initial-plan/summarise-identified-need/routes.ts, server/routes/journeys/develop-an-initial-plan/summarise-identified-need/schemas.ts, server/routes/journeys/develop-an-initial-plan/summarise-identified-need/tests.cy.ts, server/routes/journeys/develop-an-initial-plan/summarise-identified-need/view.njk
=> MIC-447 /develop-an-initial-plan/summarise-identified-need screen

integration_tests/mockApis/csipApi.ts, server/@types/express/index.d.ts, server/routes/journeys/base/controller.ts, server/routes/journeys/develop-an-initial-plan/record-actions-progress/controller.ts, server/routes/journeys/develop-an-initial-plan/record-actions-progress/routes.ts, server/routes/journeys/develop-an-initial-plan/record-actions-progress/schemas.ts, server/routes/journeys/develop-an-initial-plan/record-actions-progress/tests.cy.ts, server/routes/journeys/develop-an-initial-plan/record-actions-progress/view.njk, server/routes/journeys/develop-an-initial-plan/routes.ts, server/routes/journeys/develop-an-initial-plan/summarise-identified-need/controller.ts, server/routes/journeys/develop-an-initial-plan/summarise-identified-need/view.njk, server/routes/journeys/develop-an-initial-plan/view.njk, server/routes/journeys/screen/tests.cy.ts, server/utils/utils.ts
=> MIC-449 develop-an-initial-plan/record-actions-progress screen

package-lock.json, server/@types/csip/csipApiTypes.ts, server/@types/csip/index.d.ts, server/routes/csip-records/controller.ts, server/routes/csip-records/routes.ts, server/routes/index.ts, server/routes/prisoners/controller.ts, server/routes/prisoners/routes.ts, server/routes/prisoners/view.njk, server/services/csipApi/csipApiClient.ts, server/services/csipApi/csipApiService.ts, server/utils/csipDisplayTextUtils.ts, server/views/partials/simplePagination/macro.njk
=> Add placeholder /prisoners/:prisonNumber screen

server/routes/journeys/record-investigation/check-answers/tests.cy.ts, server/routes/journeys/record-investigation/check-answers/view.njk, server/routes/journeys/record-investigation/tests.cy.ts, server/routes/journeys/record-investigation/view.njk
MIC-486
Investigation CYA page:
Confirm and submit report -> Confirm and save report
MIC-485
Investigation CYA page:
add section break
MIC-484
Investigation tasklist page:
Confirm and submit report -> Confirm and save report
=> MIC-486 MIC-485 MIC-484 Minor UI remediations

server/routes/csip-records/components/investigation.njk, server/routes/csip-records/components/referral.njk, server/routes/csip-records/view.njk, server/routes/journeys/record-investigation/confirmation/view.njk, server/routes/journeys/referral/involvement/view.njk, server/routes/journeys/screen/confirmation/view.njk
MIC-482
missing `.` on /screen/confirmation 
MIC-480
h1 heading size change from L to XL on /csip-records/:recordUuid
MIC-479
Referrer date -> Referral Date on /csip-records/:recordUuid
=> MIC-482 MIC-480 MIC-479 Minor UI changes

server/@types/express/index.d.ts, server/app.ts, server/middleware/breadcrumbs.ts, server/routes/journeys/develop-an-initial-plan/delete-identified-need/controller.ts, server/routes/journeys/develop-an-initial-plan/intervention-details/controller.ts, server/routes/journeys/develop-an-initial-plan/intervention-details/tests.cy.ts, server/routes/journeys/develop-an-initial-plan/record-actions-progress/controller.ts, server/routes/journeys/develop-an-initial-plan/record-actions-progress/tests.cy.ts, server/routes/journeys/develop-an-initial-plan/summarise-identified-need/controller.ts, server/routes/journeys/develop-an-initial-plan/summarise-identified-need/tests.cy.ts, server/routes/journeys/record-decision/confirmation/tests.cy.ts, server/routes/journeys/record-investigation/confirmation/tests.cy.ts, server/routes/journeys/record-investigation/delete-interview/controller.ts, server/routes/journeys/record-investigation/delete-interview/tests.cy.ts, server/routes/journeys/record-investigation/interview-details/controller.ts, server/routes/journeys/record-investigation/interview-details/tests.cy.ts, server/routes/journeys/referral/confirmation/tests.cy.ts, server/routes/journeys/screen/confirmation/tests.cy.ts, server/views/pages/not-found.njk
=> MIC-489 MIC-488 Change 404 page and breadcrumb

server/routes/journeys/develop-an-initial-plan/intervention-details/controller.ts, server/routes/journeys/develop-an-initial-plan/intervention-details/tests.cy.ts, server/routes/journeys/develop-an-initial-plan/intervention-details/view.njk, server/routes/journeys/develop-an-initial-plan/next-review-date/controller.ts, server/routes/journeys/develop-an-initial-plan/next-review-date/tests.cy.ts
Fixed spacing on identified needs details page
Fix for test on record-next-date page
=> MIC-495: DaiP: Identified need summary spacing on Intervention Details

server/routes/journeys/develop-an-initial-plan/delete-identified-need/view.njk
=> Fixed button alignment

server/routes/csip-records/components/referral.njk, server/routes/csip-records/controller.ts, server/routes/csip-records/csip-records.cy.ts, server/routes/csip-records/tests.test.ts, server/routes/csip-records/view.njk, server/routes/journeys/develop-an-initial-plan/next-review-date/tests.cy.ts
=> MIC-498: CSIP Record Page with updated CTA and Summary Cards

server/@types/express/index.d.ts, server/routes/csip-records/components/decision.njk, server/routes/journeys/develop-an-initial-plan/identified-needs/view.njk, server/routes/journeys/develop-an-initial-plan/record-actions-progress/schemas.ts, server/routes/journeys/record-decision/additional-information/schemas.ts, server/routes/journeys/record-decision/next-steps/schemas.ts, server/routes/journeys/record-investigation/interview-details/schemas.ts, server/routes/journeys/referral/additional-information/schemas.ts, server/routes/journeys/referral/contributory-factors-comments/view.njk, server/routes/journeys/referral/involvement/schemas.ts, server/routes/journeys/referral/involvement/tests.cy.ts
=> MIC-519 Fix whitespace check on optional text input

server/routes/journeys/referral/proactive-or-reactive/view.njk, server/routes/journeys/update-referral/proactive-or-reactive/controller.ts, server/routes/journeys/update-referral/proactive-or-reactive/routes.ts, server/routes/journeys/update-referral/proactive-or-reactive/tests.cy.ts, server/routes/journeys/update-referral/routes.ts
=> MIC-502 /update-referral/proactive-or-reactive screen

README.md, package-lock.json, server/routes/journeys/base/patchReferralController.ts, server/routes/journeys/referral/details/controller.ts, server/routes/journeys/referral/details/details.cy.ts, server/routes/journeys/referral/details/view.njk, server/routes/journeys/referral/involvement/controller.ts, server/routes/journeys/referral/involvement/schemas.ts, server/routes/journeys/referral/involvement/tests.cy.ts, server/routes/journeys/update-referral/details/controller.ts, server/routes/journeys/update-referral/details/routes.ts, server/routes/journeys/update-referral/details/tests.cy.ts, server/routes/journeys/update-referral/involvement/controller.ts, server/routes/journeys/update-referral/routes.ts, server/utils/utils.ts
=> MIC-503 /update-referral/details screen

integration_tests/mockApis/csipApi.ts, server/routes/csip-records/components/screening.njk, server/routes/csip-records/csip-records.cy.ts
=> MIC-552: display Not Provided for empty screening reason decision

integration_tests/mockApis/csipApi.ts, server/routes/csip-records/components/referral.njk, server/routes/csip-records/controller.ts, server/routes/csip-records/view.njk, server/routes/journeys/edit-log-code/controller.ts, server/routes/journeys/edit-log-code/routes.ts, server/routes/journeys/edit-log-code/schemas.ts, server/routes/journeys/edit-log-code/start/routes.ts, server/routes/journeys/edit-log-code/tests.cy.ts, server/routes/journeys/edit-log-code/view.njk, server/routes/journeys/routes.ts, server/utils/csipDisplayTextUtils.ts, server/utils/nunjucksSetup.ts, server/views/partials/statusTag/macro.njk
=> MIC-569 Add /edit-log-code screen

server/routes/csip-records/components/investigation.njk, server/routes/journeys/record-investigation/usual-behaviour-presentation/controller.ts, server/routes/journeys/record-investigation/usual-behaviour-presentation/routes.ts, server/routes/journeys/record-investigation/usual-behaviour-presentation/schemas.ts, server/routes/journeys/record-investigation/usual-behaviour-presentation/view.njk, server/routes/journeys/update-investigation/routes.ts, server/routes/journeys/update-investigation/usual-behaviour-presentation/controller.ts, server/routes/journeys/update-investigation/usual-behaviour-presentation/routes.ts, server/routes/journeys/update-investigation/usual-behaviour-presentation/tests.cy.ts
=> MIC-578 /update-investigation/usual-behaviour-presentation screen

server/errorHandler.test.ts, server/errorHandler.ts, server/routes/testutils/appSetup.ts
=> Fix 404 error handling

server/routes/journeys/base/patchDecisionController.ts, server/routes/journeys/routes.ts, server/routes/journeys/update-decision/controller.ts, server/routes/journeys/update-decision/routes.ts, server/routes/journeys/update-decision/start/routes.ts
=> Create route for /update-decision 

server/routes/journeys/record-decision/next-steps/routes.ts, server/routes/journeys/record-decision/next-steps/schemas.ts, server/routes/journeys/record-decision/next-steps/tests.cy.ts, server/routes/journeys/record-decision/next-steps/view.njk, server/routes/journeys/update-decision/next-steps/controller.ts, server/routes/journeys/update-decision/next-steps/routes.ts, server/routes/journeys/update-decision/next-steps/tests.cy.ts, server/routes/journeys/update-decision/routes.ts
=> MIC-584: UaI: Decision next steps

server/@types/csip/index.d.ts, server/routes/journeys/base/patchPlanController.ts, server/routes/journeys/routes.ts, server/routes/journeys/update-plan/controller.ts, server/routes/journeys/update-plan/routes.ts, server/routes/journeys/update-plan/start/routes.ts, server/services/csipApi/csipApiClient.ts, server/services/csipApi/csipApiService.ts, server/utils/sorters.ts
=> MIC-617 Add routes for /update-plan/start

integration_tests/mockApis/csipApi.ts, server/routes/csip-records/components/plan.njk, server/routes/journeys/base/patchPlanController.ts, server/routes/journeys/update-plan/case-management/controller.ts, server/routes/journeys/update-plan/case-management/routes.ts, server/routes/journeys/update-plan/case-management/schemas.ts, server/routes/journeys/update-plan/case-management/tests.cy.ts, server/routes/journeys/update-plan/case-management/view.njk, server/routes/journeys/update-plan/controller.ts, server/routes/journeys/update-plan/routes.ts
=> MIC-619: Update a Plan - Case Management

server/routes/csip-records/components/plan.njk, server/routes/csip-records/view.njk, server/routes/journeys/update-plan/controller.ts, server/routes/journeys/update-plan/routes.ts, server/routes/journeys/update-plan/start/routes.ts, server/routes/journeys/update-plan/tests.cy.ts, server/utils/csipDisplayTextUtils.ts, server/utils/nunjucksSetup.ts
=> MIC-617 /update-plan view

integration_tests/mockApis/csipApi.ts, server/@types/express/index.d.ts, server/routes/csip-records/components/plan.njk, server/routes/journeys/base/patchPlanController.ts, server/routes/journeys/update-plan/controller.ts, server/routes/journeys/update-plan/identified-needs/controller.ts, server/routes/journeys/update-plan/identified-needs/view.njk, server/routes/journeys/update-plan/routes.ts, server/routes/journeys/update-plan/tests.cy.ts, server/routes/journeys/update-plan/update-intervention-details/controller.ts, server/routes/journeys/update-plan/update-intervention-details/routes.ts, server/routes/journeys/update-plan/update-intervention-details/schemas.ts, server/routes/journeys/update-plan/update-intervention-details/tests.cy.ts, server/routes/journeys/update-plan/update-intervention-details/view.njk, server/services/csipApi/csipApiClient.ts
=> MIC-625 /update-plan/update-intervention-details screen

server/routes/journeys/develop-an-initial-plan/intervention-details/view.njk, server/routes/journeys/update-plan/identified-needs/view.njk, server/routes/journeys/update-plan/intervention-details/controller.ts, server/routes/journeys/update-plan/intervention-details/routes.ts, server/routes/journeys/update-plan/intervention-details/tests.cy.ts, server/routes/journeys/update-plan/routes.ts
=> MIC-631 update-plan/intervention-details screen

server/@types/csip/index.d.ts, server/routes/journeys/base/patchPlanController.ts, server/routes/journeys/update-plan/reopen-identified-need/controller.ts, server/routes/journeys/update-plan/reopen-identified-need/routes.ts, server/routes/journeys/update-plan/reopen-identified-need/tests.cy.ts, server/routes/journeys/update-plan/reopen-identified-need/view.njk, server/routes/journeys/update-plan/routes.ts
=> MIC-629: UaP: Reopen identified need

server/@types/express/index.d.ts, server/routes/csip-records/controller.ts, server/routes/journeys/record-review/controller.ts, server/routes/journeys/record-review/routes.ts, server/routes/journeys/record-review/start/routes.ts, server/routes/journeys/record-review/start/tests.cy.ts, server/routes/journeys/record-review/tests.cy.ts, server/routes/journeys/record-review/view.njk, server/routes/journeys/routes.ts, server/routes/journeys/start/controller.ts
=> MIC-666: RaR: Record a CSIP review

server/routes/journeys/record-review/outcome/controller.ts, server/routes/journeys/record-review/outcome/routes.ts, server/routes/journeys/record-review/outcome/schemas.ts, server/routes/journeys/record-review/outcome/tests.cy.ts, server/routes/journeys/record-review/outcome/view.njk, server/routes/journeys/record-review/routes.ts
=> MIC-671: RaR: Outcome

server/@types/express/index.d.ts, server/routes/csip-records/components/reviews.njk, server/routes/index.ts, server/routes/journeys/base/patchReferralController.ts, server/routes/journeys/base/patchReviewController.ts, server/routes/journeys/record-review/check-answers/tests.cy.ts, server/routes/journeys/record-review/check-answers/view.njk, server/routes/journeys/record-review/close-csip/controller.ts, server/routes/journeys/record-review/next-review-date/controller.ts, server/routes/journeys/record-review/outcome/controller.ts, server/routes/journeys/record-review/outcome/view.njk, server/routes/journeys/update-review/controller.ts, server/routes/journeys/update-review/outcome/controller.ts, server/routes/journeys/update-review/outcome/tests.cy.ts, server/utils/utils.ts
fix routes related to record-review/outcome and update-review/outcome, and
remove Update review links on closed CSIP, and
fix Patch referral request
=> remediation on review/outcome

integration_tests/mockApis/csipApi.ts, server/routes/journeys/record-review/details/controller.ts, server/routes/journeys/record-review/details/routes.ts, server/routes/journeys/record-review/details/schemas.ts, server/routes/journeys/record-review/details/view.njk, server/routes/journeys/update-review/details/controller.ts, server/routes/journeys/update-review/details/routes.ts, server/routes/journeys/update-review/details/tests.cy.ts, server/routes/journeys/update-review/routes.ts
=> MIC-686: UaR: Enter review details

server/routes/csip-records/components/proactive.njk, server/routes/csip-records/components/reactive.njk, server/routes/csip-records/components/referral.njk, server/routes/csip-records/components/reviews.njk, server/routes/csip-records/controller.ts, server/routes/csip-records/csip-records.cy.ts, server/routes/journeys/record-review/check-answers/controller.ts, server/routes/journeys/record-review/check-answers/tests.cy.ts, server/routes/journeys/record-review/check-answers/view.njk, server/routes/journeys/referral/check-answers/components/proactive.njk, server/routes/journeys/referral/check-answers/components/reactive.njk, server/routes/journeys/referral/check-answers/controller.ts, server/routes/journeys/referral/check-answers/view.njk, server/routes/journeys/update-referral/controller.ts, server/routes/journeys/update-review/view.njk, server/utils/nunjucksSetup.ts
=> Enable Update referral link on REFERRAL_PENDING record

server/routes/csip-records/components/referral.njk, server/routes/csip-records/components/reviews.njk, server/routes/journeys/update-review/view.njk, server/utils/appendFieldUtils.test.ts, server/utils/appendFieldUtils.ts, server/utils/utils.test.ts, server/utils/utils.ts
Fix append stamp edge case where there is no existing text
edge case of empty contributory factor list
edge case of empty attendee list
=> Append stamp fix

integration_tests/mockApis/csipApi.ts, server/routes/journeys/base/patchCsipRecordController.ts, server/routes/journeys/base/patchReferralController.ts, server/routes/journeys/base/patchReviewController.ts, server/routes/journeys/edit-log-code/controller.ts, server/routes/journeys/record-review/participant-contribution-details/routes.ts, server/routes/journeys/record-review/participant-contribution-details/schemas.ts, server/routes/journeys/record-review/participant-contribution-details/view.njk, server/routes/journeys/update-plan/update-identified-need/controller.ts, server/routes/journeys/update-review/routes.ts, server/routes/journeys/update-review/tests.cy.ts, server/routes/journeys/update-review/update-participant-contribution-details/controller.ts, server/routes/journeys/update-review/update-participant-contribution-details/routes.ts, server/routes/journeys/update-review/update-participant-contribution-details/tests.cy.ts, server/routes/journeys/update-review/view.njk
=> MIC-690 /update-review/update-participant-contribution-details screen

server/routes/journeys/base/patchReviewController.ts, server/routes/journeys/record-review/close-csip/view.njk, server/routes/journeys/update-review/close-csip/controller.ts, server/routes/journeys/update-review/close-csip/routes.ts, server/routes/journeys/update-review/close-csip/tests.cy.ts, server/routes/journeys/update-review/details/controller.ts, server/routes/journeys/update-review/next-review-date/controller.ts, server/routes/journeys/update-review/next-review-date/tests.cy.ts, server/routes/journeys/update-review/routes.ts
=> MIC-688: UaR: Close CSIP

server/routes/csip-records/components/investigation.njk, server/routes/csip-records/controller.ts, server/routes/csip-records/view.njk, server/routes/journeys/update-investigation/controller.ts
=> Fix /csip-records/recordUuid screen's tabs

integration_tests/e2e/screen-a-csip.cy.ts, integration_tests/mockApis/componentsApi.ts, server/interfaces/hmppsUser.ts, server/middleware/checkPopulateUserCaseloads.ts, server/routes/journeys/base/components/view-other-csips.njk, server/routes/journeys/screen/confirmation/controller.ts, server/routes/journeys/screen/confirmation/tests.cy.ts, server/routes/journeys/screen/confirmation/view.njk, server/utils/azureAppInsights.ts
=> MIC-733 Update /screen/confirmation

integration_tests/e2e/make-a-referral.cy.ts, server/routes/controller.ts, server/routes/journeys/develop-an-initial-plan/confirmation/controller.ts, server/routes/journeys/develop-an-initial-plan/confirmation/tests.cy.ts, server/routes/journeys/develop-an-initial-plan/confirmation/view.njk, server/routes/journeys/record-decision/confirmation/controller.ts, server/routes/journeys/record-decision/confirmation/tests.cy.ts, server/routes/journeys/record-decision/confirmation/view.njk, server/routes/journeys/record-review/check-answers/controller.ts, server/routes/journeys/record-review/confirmation/controller.ts, server/routes/journeys/record-review/confirmation/tests.cy.ts, server/routes/journeys/record-review/confirmation/view.njk, server/routes/journeys/referral/confirmation/tests.cy.ts, server/routes/journeys/referral/confirmation/view.njk
MIC-732
MIC-735
MIC-736
MIC-737
=> Update various confirmation screens

server/routes/journeys/record-investigation/confirmation/tests.cy.ts, server/routes/journeys/record-investigation/confirmation/view.njk
=> MIC-734: Investigation confirmation screens

server/routes/csip-records/components/investigation.njk, server/routes/csip-records/view.njk, server/routes/journeys/record-decision/additional-information/tests.cy.ts, server/routes/journeys/record-decision/additional-information/view.njk, server/routes/journeys/record-decision/check-answers/tests.cy.ts, server/routes/journeys/record-decision/check-answers/view.njk, server/routes/journeys/record-decision/conclusion/tests.cy.ts, server/routes/journeys/record-decision/conclusion/view.njk, server/routes/journeys/record-decision/confirmation/tests.cy.ts, server/routes/journeys/record-decision/confirmation/view.njk, server/routes/journeys/record-decision/next-steps/tests.cy.ts, server/routes/journeys/record-decision/next-steps/view.njk, server/routes/journeys/record-decision/tests.cy.ts, server/routes/journeys/record-decision/view.njk, server/routes/journeys/update-decision/additional-information/tests.cy.ts, server/routes/journeys/update-decision/conclusion/tests.cy.ts, server/routes/journeys/update-decision/conclusion/view.njk, server/routes/journeys/update-decision/next-steps/tests.cy.ts
=> MIC-757: Make/Update a CSIP decision amends

server/middleware/setUpWebSecurity.ts
=> MIC-639: Add app insights client side telemetry JavaScript to content security policy

integration_tests/mockApis/csipApi.ts, server/routes/manage-csips/controller.ts, server/routes/manage-csips/tests.cy.ts
=> Fix redirect loop on manage-csips

server/routes/csip-records/components/decision.njk, server/routes/csip-records/components/investigation.njk, server/routes/csip-records/components/proactive.njk, server/routes/csip-records/components/reactive.njk, server/routes/csip-records/components/referral.njk, server/routes/journeys/update-decision/controller.ts, server/routes/journeys/update-decision/tests.cy.ts, server/routes/journeys/update-investigation/controller.ts, server/routes/journeys/update-investigation/tests.cy.ts, server/routes/journeys/update-referral/controller.ts, server/routes/journeys/update-referral/tests.cy.ts, server/utils/nunjucksSetup.ts, server/utils/viewUtils.ts
=> MIC-837: Character limit warning message

assets/js/index.js, server/routes/journeys/edit-log-code/tests.cy.ts
=> MIC-889 prevent line break on single-row textarea components

server/routes/manage-csips/view.njk
=> MIC-899: Remove Support through ACCT from the filter list on Manage a CSIP Caseload

server/routes/csip-records/components/reviews.njk, server/routes/csip-records/csip-records.cy.ts
=> MIC-912: Add next review date to CSIP reviews

.circleci/config.yml
Disable Slack notifications for pre-prod and prod deployments
=> MIC-949: Disable Slack notifications

assets/scss/local.scss, package-lock.json, server/routes/manage-csips/components/filters.ts, server/routes/manage-csips/tests.cy.ts, server/routes/manage-csips/view.njk
=> MIAD-355: Sortable column headers have redundant annoucements

server/routes/manage-csips/components/filters.ts, server/routes/manage-csips/tests.cy.ts
=> MIAD-357: Fix double tabbing on column headers

assets/scss/components/_summary-card.scss, server/routes/csip-records/components/decision.njk, server/routes/csip-records/components/investigation.njk, server/routes/csip-records/components/plan.njk, server/routes/csip-records/components/proactive.njk, server/routes/csip-records/components/reactive.njk, server/routes/csip-records/components/referral.njk, server/routes/csip-records/components/reviews.njk, server/routes/csip-records/components/screening.njk, server/routes/csip-records/csip-records.cy.ts, server/routes/journeys/record-review/check-answers/tests.cy.ts, server/routes/journeys/record-review/check-answers/view.njk, server/routes/journeys/record-review/confirmation/tests.cy.ts, server/routes/journeys/record-review/confirmation/view.njk, server/routes/journeys/referral/check-answers/components/proactive.njk, server/routes/journeys/referral/check-answers/components/reactive.njk, server/routes/journeys/referral/check-answers/tests.cy.ts, server/routes/journeys/referral/check-answers/view.njk, server/routes/journeys/referral/confirmation/tests.cy.ts, server/routes/journeys/referral/confirmation/view.njk, server/routes/tests.cy.ts, server/routes/view.njk
No visual changes here - purely semantic heading hierarchy
=> MIAD-367: Fix heading hierarchy 

assets/scss/local.scss, cypress.config.ts, integration_tests/mockApis/csipApi.ts, server/@types/csip/index.d.ts, server/@types/express/index.d.ts, server/routes/index.ts, server/routes/manage-csips/components/filters.ts, server/routes/manage-csips/controller.ts, server/routes/manage-csips/tests.cy.ts, server/routes/manage-csips/view.njk, server/services/csipApi/csipApiClient.ts, server/services/csipApi/csipApiService.ts, server/utils/nunjucksSetup.ts
Manage CSIPs (original page)
Manage Referrals
Manage Plans
=> MIA-513: CSIP Caseload

integration_tests/mockApis/csipApi.ts, server/routes/csip-records/components/decision.njk, server/routes/csip-records/components/decisionSummaryList.njk, server/routes/csip-records/components/screening.njk, server/routes/csip-records/components/screeningSummaryList.njk, server/routes/csip-records/csip-records.cy.ts
=> MIAD-518: CSIP record conditional view for historic decisions

assets/scss/local.scss, server/routes/csip-records/csip-records.cy.ts, server/routes/journeys/develop-an-initial-plan/check-answers/tests.cy.ts, server/routes/journeys/develop-an-initial-plan/intervention-details/tests.cy.ts, server/routes/journeys/develop-an-initial-plan/intervention-details/view.njk, server/routes/journeys/develop-an-initial-plan/record-actions-progress/tests.cy.ts, server/routes/journeys/develop-an-initial-plan/record-actions-progress/view.njk, server/routes/journeys/update-plan/update-intervention-details/tests.cy.ts, server/routes/journeys/update-plan/update-intervention-details/view.njk
=> MIAD-537: Wrap identified need text

assets/scss/application.scss, assets/scss/local.scss, package-lock.json, package.json, server/routes/manage-csips/view.njk, server/views/partials/sortableTable/_index.scss, server/views/partials/sortableTable/macro.njk, server/views/partials/sortableTable/template.njk
=> MIAD-539: Upgrade CSIP MoJ Frontend library to v5

server/@types/express/index.d.ts, server/app.ts, server/data/hmppsAuditClient.test.ts, server/data/hmppsAuditClient.ts, server/middleware/auditPageViewMiddleware.ts, server/middleware/populateAuditEventDetails.ts, server/middleware/populateAuditEventDetailsForPostRequests.ts, server/middleware/populatePrisonerSummary.ts, server/routes/journeys/base/patchCsipRecordController.ts, server/routes/journeys/base/patchDecisionController.ts, server/routes/journeys/base/patchInvestigationController.ts, server/routes/journeys/base/patchPlanController.ts, server/routes/journeys/base/patchReviewController.ts, server/routes/journeys/base/updateReferralContributoryFactorController.ts, server/routes/journeys/change-decision/check-answers/controller.ts, server/routes/journeys/change-screen/check-answers/controller.ts, server/routes/journeys/develop-an-initial-plan/check-answers/controller.ts, server/routes/journeys/record-decision/check-answers/controller.ts, server/routes/journeys/record-investigation/check-answers/controller.ts, server/routes/journeys/record-review/check-answers/controller.ts, server/routes/journeys/referral/check-answers/controller.ts, server/routes/journeys/screen/check-answers/controller.ts, server/routes/journeys/update-plan/check-answers/controller.ts, server/routes/journeys/update-referral/new-contributory-factor-comment/controller.ts, server/services/auditService.test.ts, server/services/auditService.ts
=> MIAD-529 Update HMPPS Audit events

.github/workflows/parallel_integration_tests.yml, .github/workflows/pipeline.yml, cypress.config.ts, package-lock.json, package.json, tsconfig.json
1. Split cypress tests to run in parallel in CI pipeline
2. Add codecoverage report
=> Split cypress tests to run in parallel in CI pipeline

assets/scss/components/_print-view.scss, server/routes/csip-records/csip-records.cy.ts, server/routes/csip-records/view.njk
=> MIAD-601 Revamp print button function

server/routes/csip-records/controller.ts, server/routes/csip-records/csip-records.cy.ts, server/routes/csip-records/view.njk
=> MIAD-614 Allow all DPS user to record/update investigation

integration_tests/mockApis/csipApi.ts, server/@types/csip/index.d.ts, server/routes/csip-records/components/plan.njk, server/routes/csip-records/csip-records.cy.ts, server/routes/journeys/develop-an-initial-plan/e2e.cy.ts, server/routes/journeys/develop-an-initial-plan/record-actions-progress/routes.ts, server/routes/journeys/develop-an-initial-plan/record-actions-progress/schemas.ts, server/routes/journeys/develop-an-initial-plan/record-actions-progress/tests.cy.ts, server/routes/journeys/develop-an-initial-plan/record-actions-progress/view.njk, server/routes/journeys/update-plan/check-answers/tests.cy.ts, server/routes/journeys/update-plan/record-actions-progress/controller.ts, server/routes/journeys/update-plan/record-actions-progress/routes.ts, server/routes/journeys/update-plan/record-actions-progress/tests.cy.ts, server/utils/nunjucksSetup.ts, server/utils/utils.ts
=> MIA-524-MIA-556: Plan date additions and Actions and Progress content updates

CODEOWNERS
=> LSM-137 - Codeowners
